Repository purduesigbots/pros, pull requests merged in 2019-02, with the labels that each got.

#94 👷‍♂️ Add Azure Pipelines for building templates
  README.md
  azure-pipelines.yml
Labels: in progress, p: low

#100 🐛 Refactor task_notify_when_deleting to support task_to_notify dying before target_task
  include/pros/apix.h
  include/rtos/FreeRTOSConfig.h
  src/rtos/task_notify_when_deleting.c
  src/system/rtos_hooks.c
Labels: bug, in testing, p: high

#107 🐛 Add LLEMU read buttons nullcheck
  src/display/llemu.c
Labels: bug, in progress, p: normal

#111 👷‍♂️ Re-order make execution after updating build number
  azure-pipelines.yml
  version.py
Labels: bug, in progress, p: low

#113 🤦‍♀️ Dot between build ID and commit on Azure Pipelines
  version.py
Labels: bug, p: unbreak now!

#98 🐛 Prevent Buffer Overrun in Controller Printing
  src/devices/controller.c
Labels: bug, in testing, p: low

#119 Don't include timestamp in cold image
  common.mk
Labels: bug, p: unbreak now!

#121 ✨ Add Makefile-variable for exclude cold image
  common.mk
  template-Makefile
Labels: enhancement, in testing
