Repository purduesigbots/pros, pull requests merged in 2019-08, with the labels that each got.

#154 🔧 Enable hot/cold by default
  template-Makefile
Labels: enhancement, p: normal

#151 🐛 Fix multiple ADI bugs and inconsistencies
  VSCode.md
  include/pros/adi.h
  include/pros/adi.hpp
  include/vdml/vdml.h
  src/devices/vdml_adi.c
  src/devices/vdml_adi.cpp
Labels: bug, optimization, p: normal

#158 🚸 Add alternate constructor for pros::Task
  include/pros/rtos.hpp
  src/rtos/rtos.cpp
Labels: enhancement, in progress, p: normal
