Repository purduesigbots/pros, pull requests merged in 2020-01, with the labels that each got.

#191 🐛Fix header tracking of duplicate basename files
  common.mk
Labels: enhancement, in testing, p: normal

#198 ✨ Enable LVGL keyboard
  include/display/lv_conf.h
Labels: feature, in testing, p: low

#188 ✨ Add a new class method: get_port
  include/pros/motors.hpp
  include/pros/serial.hpp
  include/pros/vision.hpp
  src/devices/vdml_motors.cpp
  src/devices/vdml_serial.cpp
  src/devices/vdml_vision.cpp
Labels: enhancement, p: low

#199 💡 Fix ultrasonic docs
  include/pros/adi.h
  include/pros/adi.hpp
Labels: enhancement, in testing, p: low
